---
# tasks file for docker
- name: create image docker
  docker_image:
    name: ghofhad/Myappl
    build:
     path: /var/lib/jenkins/workspace/CD-pipeline
     pull: no
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: ag_myapp_container
    image: ghofhad/Myappl:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
